market:
    resource: "@MarketBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     "fleamarket.%domain%"

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /
