<?php

namespace MarketBundle\Entity;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllNonEmpty()
    {
        return $this->createQueryBuilder('cat')
            ->join('MarketBundle:Item', 'i', 'WITH', 'cat.slug=i.category')
            ->groupBy('cat.name')
            ->getQuery()
            ->getResult();
    }
}
