<?php

namespace MarketBundle\Entity;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFree()
    {
        return $this->createQueryBuilder('i')
            ->where("i.price=0")
            ->getQuery()
            ->getResult();
    }

    public function findCategory($cat)
    {
        return $this->createQueryBuilder('i')
            ->where("i.category=:category")
            ->setParameter('category', $cat)
            ->getQuery()
            ->getResult();
    }
}
